#ifndef TAKELINE_GLOBAL_H
#define TAKELINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TAKELINE_LIBRARY)
#  define TAKELINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TAKELINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TAKELINE_GLOBAL_H
