#ifndef CLITEMPLETE_GLOBAL_H
#define CLITEMPLETE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLITEMPLETE_LIBRARY)
#  define CLITEMPLETE_EXPORT Q_DECL_EXPORT
#else
#  define CLITEMPLETE_EXPORT Q_DECL_IMPORT
#endif

#endif // CLITEMPLETE_GLOBAL_H
